[debian-minimal-rootfs-x86_64]
git-tree-sha1 = "4d66e139e0bcfdfa5ec6a8942a938e754e17860f"
lazy = true

    [[debian-minimal-rootfs-x86_64.download]]
    sha256 = "da7d20f2c4ada16db37a518fc2328ccf17d45d9b43fbae7d5cfb72fcde25219d"
    url = "https://github.com/JuliaCI/rootfs-images/releases/download/v5.45/debian_minimal.x86_64.tar.gz"

[debian-minimal-rootfs-i686]
git-tree-sha1 = "80ffa08dc6ab7fbb49ab4ca95c3e167be3127f26"
lazy = true

    [[debian-minimal-rootfs-i686.download]]
    sha256 = "543eb311c6ea551287f67353be1dbb6e4079d991233174a4daab9e34078a9885"
    url = "https://github.com/JuliaCI/rootfs-images/releases/download/v5.45/debian_minimal.i686.tar.gz"

[debian-minimal-rootfs-aarch64]
git-tree-sha1 = "792c9f5b7366dba290cb4cb0755094085d245891"
lazy = true

    [[debian-minimal-rootfs-aarch64.download]]
    sha256 = "47c1ca4494013acddbff347856f3f61a3d1e0d61d7a04833fb75f2b95e01f9b4"
    url = "https://github.com/JuliaCI/rootfs-images/releases/download/v5.45/debian_minimal.aarch64.tar.gz"

[debian-minimal-rootfs-armv7l]
git-tree-sha1 = "eb097fdfa2f3de418da8f631ef5243e0c8ac4845"
lazy = true

    [[debian-minimal-rootfs-armv7l.download]]
    sha256 = "2d3c5ab50bc9fabceb0d456be35f65128af0f1491fb126165555dd8d8d7e4307"
    url = "https://github.com/JuliaCI/rootfs-images/releases/download/v5.45/debian_minimal.armv7l.tar.gz"

[debian-minimal-rootfs-powerpc64le]
git-tree-sha1 = "245064ccaf65c2a8de08c4766f6362322388eda4"
lazy = true

    [[debian-minimal-rootfs-powerpc64le.download]]
    sha256 = "ebbdc54ab02f731738a8a49e237c1e588c191eed3d894b0e3f21cddbac8eba44"
    url = "https://github.com/JuliaCI/rootfs-images/releases/download/v5.45/debian_minimal.ppc64le.tar.gz"

[multiarch-rootfs]
git-tree-sha1 = "b9bc181be08c4a0598539af7ef93340778df527c"
lazy = true

    [[multiarch-rootfs.download]]
    sha256 = "d88de5783becfc22cfd13dfa5ad965197f9bae2256e8ad89ff358adb2994b4c1"
    url = "https://github.com/staticfloat/Sandbox.jl/releases/download/multiarch-78df527c/multiarch.tar.gz"

[[multiarch-support]]
arch = "x86_64"
git-tree-sha1 = "378e2a4e3e4421d517f01b24f96f3eb2e3674774"
lazy = true
libc = "glibc"
os = "linux"

    [[multiarch-support.download]]
    sha256 = "711afa233aa47132871dd0638ef94cb6329ca9c5bb397a9622e47b19a94e50c4"
    url = "https://github.com/staticfloat/Sandbox.jl/releases/download/multiarch-support-e3674774/multiarch-support.tar.gz"

[multiarch-testing]
git-tree-sha1 = "88a9ec7a6394e96eae6304799ba03d6f65fee52d"
lazy = true

    [[multiarch-testing.download]]
    sha256 = "32aa6559ff62b9114967614a1e8947d7e385f9aaf7daa99fb7a79e9972abebb9"
    url = "https://github.com/staticfloat/Sandbox.jl/releases/download/multiarch-testing-65fee52d/multiarch-testing.tar.gz"
