[debian-minimal-rootfs-x86_64]
git-tree-sha1 = "16738e2d713323e608ff891cb66de38d9d667d45"
lazy = true

    [[debian-minimal-rootfs-x86_64.download]]
    sha256 = "5be53620d001a4907e5471689d1876dfd26f7e7d8e14af6424418218d0eb4e08"
    url = "https://github.com/JuliaCI/rootfs-images/releases/download/v5.53/debian_minimal.x86_64.tar.gz"

[debian-minimal-rootfs-i686]
git-tree-sha1 = "6acbceb9cb6e0dca4165cb0ba6935595601592a7"
lazy = true

    [[debian-minimal-rootfs-i686.download]]
    sha256 = "d69ccf1f27808593be02dfdb5c2fb93e3e5098138a25b8dcb0e5d884b8c2f707"
    url = "https://github.com/JuliaCI/rootfs-images/releases/download/v5.53/debian_minimal.i686.tar.gz"

[debian-minimal-rootfs-aarch64]
git-tree-sha1 = "14e9dcabf9b1eb2870158b06f16fc3742b53c493"
lazy = true

    [[debian-minimal-rootfs-aarch64.download]]
    sha256 = "95e703a9fe9297eebb379b42743d990f89f500fedea437fb9282809f7db4eee4"
    url = "https://github.com/JuliaCI/rootfs-images/releases/download/v5.53/debian_minimal.aarch64.tar.gz"

[debian-minimal-rootfs-armv7l]
git-tree-sha1 = "b872b7f932fd3c04945f213e484a99830aef90e5"
lazy = true

    [[debian-minimal-rootfs-armv7l.download]]
    sha256 = "dd1f98b273a5322532bd64796326b1c0132a70f4cee1ad77270e6e307a646c05"
    url = "https://github.com/JuliaCI/rootfs-images/releases/download/v5.53/debian_minimal.armv7l.tar.gz"

[debian-minimal-rootfs-powerpc64le]
git-tree-sha1 = "b77c22a4a1dff4bdde33d07fb02146ad3a58bd88"
lazy = true

    [[debian-minimal-rootfs-powerpc64le.download]]
    sha256 = "1a2293147ccf9a158b0a272ba5dee48c0206a172a002a2556fa0296a71b5cec7"
    url = "https://github.com/JuliaCI/rootfs-images/releases/download/v5.53/debian_minimal.ppc64le.tar.gz"

[multiarch-rootfs]
git-tree-sha1 = "b9bc181be08c4a0598539af7ef93340778df527c"
lazy = true

    [[multiarch-rootfs.download]]
    sha256 = "d88de5783becfc22cfd13dfa5ad965197f9bae2256e8ad89ff358adb2994b4c1"
    url = "https://github.com/staticfloat/Sandbox.jl/releases/download/multiarch-78df527c/multiarch.tar.gz"

[[multiarch-support]]
arch = "x86_64"
git-tree-sha1 = "378e2a4e3e4421d517f01b24f96f3eb2e3674774"
lazy = true
libc = "glibc"
os = "linux"

    [[multiarch-support.download]]
    sha256 = "711afa233aa47132871dd0638ef94cb6329ca9c5bb397a9622e47b19a94e50c4"
    url = "https://github.com/staticfloat/Sandbox.jl/releases/download/multiarch-support-e3674774/multiarch-support.tar.gz"

[multiarch-testing]
git-tree-sha1 = "88a9ec7a6394e96eae6304799ba03d6f65fee52d"
lazy = true

    [[multiarch-testing.download]]
    sha256 = "32aa6559ff62b9114967614a1e8947d7e385f9aaf7daa99fb7a79e9972abebb9"
    url = "https://github.com/staticfloat/Sandbox.jl/releases/download/multiarch-testing-65fee52d/multiarch-testing.tar.gz"
