[alpine-rootfs]
git-tree-sha1 = "562768a40e93d27b79fbedf9cfa7883409d494ea"
lazy = true

    [[alpine-rootfs.download]]
    sha256 = "5a588162779446d8e5235bf6fc97588d1e197f44cf64e3a1f88ae828270456a7"
    url = "https://github.com/alpinelinux/docker-alpine/raw/2f3c3015951938c521e752899a92ecd618e0c05b/x86_64/alpine-minirootfs-3.12.4-x86_64.tar.gz"

[debian-julia-python3-rootfs]
git-tree-sha1 = "c0f2c53b857189e1c8378bd37c3b620ea4843e07"
lazy = true

    [[debian-julia-python3-rootfs.download]]
    sha256 = "58b03f624a1a5b1fb52c4d58a7be62df0bf74e26fa3c160cfe0e821adcc6f7de"
    url = "https://github.com/staticfloat/Sandbox.jl/releases/download/julia-python3-77eae3ba/julia-python3.tar.gz"

[debian-minimal-rootfs]
git-tree-sha1 = "f2dd967ccbf4ab29781388f5848f8d17a4a4e0bc"
lazy = true

    [[debian-minimal-rootfs.download]]
    sha256 = "7e5f2625e6ca9a105430e0a505896184b503dfc3a7ce15916d2b8dca0391e65d"
    url = "https://github.com/JuliaCI/rootfs-images/releases/download/v4.4/debian_minimal.x86_64.tar.gz"

[julia-alpine-rootfs]
git-tree-sha1 = "2a09164e817e43448ff352b34e601f5446e8be7e"
lazy = true

    [[julia-alpine-rootfs.download]]
    sha256 = "846a3aa9350bf23ca1a2bd862c53eae12e5b570ac06f48242a047134cbba78f1"
    url = "https://github.com/staticfloat/Sandbox.jl/releases/download/julia-alpine-46e8be7e/julia_alpine.tar.gz"

[multiarch-rootfs]
git-tree-sha1 = "b9bc181be08c4a0598539af7ef93340778df527c"
lazy = true

    [[multiarch-rootfs.download]]
    sha256 = "d88de5783becfc22cfd13dfa5ad965197f9bae2256e8ad89ff358adb2994b4c1"
    url = "https://github.com/staticfloat/Sandbox.jl/releases/download/multiarch-78df527c/multiarch.tar.gz"

[[multiarch-support]]
arch = "x86_64"
git-tree-sha1 = "378e2a4e3e4421d517f01b24f96f3eb2e3674774"
lazy = true
libc = "glibc"
os = "linux"

    [[multiarch-support.download]]
    sha256 = "711afa233aa47132871dd0638ef94cb6329ca9c5bb397a9622e47b19a94e50c4"
    url = "https://github.com/staticfloat/Sandbox.jl/releases/download/multiarch-support-e3674774/multiarch-support.tar.gz"

[multiarch-testing]
git-tree-sha1 = "88a9ec7a6394e96eae6304799ba03d6f65fee52d"
lazy = true

    [[multiarch-testing.download]]
    sha256 = "32aa6559ff62b9114967614a1e8947d7e385f9aaf7daa99fb7a79e9972abebb9"
    url = "https://github.com/staticfloat/Sandbox.jl/releases/download/multiarch-testing-65fee52d/multiarch-testing.tar.gz"
