steps:
  - label: ":rocket: Launch matrix of options"
    command: |
      export ARCH JULIA_VERSION LOCAL_SANDBOX
      for ARCH in x86_64 aarch64; do
        for JULIA_VERSION in 1.6 nightly; do
          for LOCAL_SANDBOX in true false; do
            buildkite-agent pipeline upload .buildkite/test_sandbox.yml
          done
        done
      done
    agents:
      queue: "juliaecosystem"
      os: "linux"
