steps:
  - label: ":rocket: Launch matrix of options"
    command: |
      export ARCH JULIA_VERSION LOCAL_SANDBOX ROOTFS_URL ROOTFS_HASH
      for ARCH in x86_64 aarch64; do
        ROOTFS_URL="https://github.com/JuliaCI/rootfs-images/releases/download/v5.26/package_linux.$${ARCH}.tar.gz"
        if [[ "$${ARCH}" == "x86_64" ]]; then
          ROOTFS_HASH="5b0b851aca3c941b900a1301c13922c6cfc7f211"
        elif [[ "$${ARCH}" == "aarch64" ]]; then
          ROOTFS_HASH="dcf39d10ba43bf13c75d5031c3a88f125780033b"
        fi
        for JULIA_VERSION in 1.7 1 nightly; do
          for LOCAL_SANDBOX in true false; do
            buildkite-agent pipeline upload .buildkite/test_sandbox.yml
          done
        done
      done
    agents:
      queue: "juliaecosystem"
      os: "linux"
