steps:
  - label: ":julia: Test on Julia ${JULIA_VERSION}, arch ${ARCH}, local sandbox: ${LOCAL_SANDBOX}"
    plugins:
      # Install Julia
      - JuliaCI/julia#v1:
          version: "${JULIA_VERSION}"
      # Run inside of a rootfs that allows us to build the local sandbox, also that maps to a non-zero UID
      - staticfloat/sandbox#v2:
          rootfs_url: "${ROOTFS_URL?}"
          rootfs_treehash: "${ROOTFS_HASH?}"
          uid: 1000
          gid: 1000
          workspaces:
            - "/cache:/cache"

      # Run standard tests, possibly building a local sandbox
      - JuliaCI/julia-test#v1: ~

     # Disabled for now, pending tokenless uploads, or integration of a codecov token
     #- JuliaCI/julia-coverage#v1:
     #    codecov: true
    env:
      SANDBOX_BUILD_LOCAL_SANDBOX: "${LOCAL_SANDBOX}"
      # Because `binfmt_misc` can't be manipulated within a sandbox, we
      # just disable the `binfmt_misc` tests within nested sandbox environments,
      # of which all buildkite agents are.
      SANDBOX_TEST_MULTIARCH: false
    # Only run on agents that are already using `sandbox.jl`, as then we know we can nest
    agents:
      queue: "juliaecosystem"
      sandbox_capable: "true"
      arch: "${ARCH}"
