# Only run on agents that are using sandbox.jl
agents:
  queue: "julia"
  sandbox.jl: "true"

steps:
  - label: ":julia: Test on Julia ${JULIA_VERSION}, local sandbox: ${LOCAL_SANDBOX}"
    plugins:
      # Install Julia
      - JuliaCI/julia#v1:
          version: "${JULIA_VERSION}"
      # Install `gcc` so that we can build the local sandbox, and `sudo` so that we can test the privileged runner
      - improbable-eng/metahook:
          pre-command: apt install -y gcc sudo
      # Run standard tests, possibly building a local sandbox
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          codecov: true
    env:
      SANDBOX_BUILD_LOCAL_SANDBOX: "${LOCAL_SANDBOX}"
      # Because `binfmt_misc` can't be manipulated within a sandbox, we
      # just disable the `binfmt_misc` tests within nested sandbox environments,
      # of which all buildkite agents are.
      SANDBOX_TEST_MULTIARCH: false
